### ISSUE TITLE
Logging is indiscriminately being sent to both files

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operation_code_pybot#16]
When you wish to log an event with `new_event_logger.info('something')` it's being sent as if you wanted to send it to both `new_event_logger` and `all_event_logger` Even if you only send the string to one of the loggers.

**Comment by wimo7083** [comment]
Need to verify this now that we had a large push. Will probably transition logging methods later.  Make this part of refactor and interaction data.

**Comment by AllenAnthes** [comment]
Logging doesn't appear to be functioning on deployment server

**Comment by AllenAnthes** [comment]
Logging is now being sent to the default PythonAnywhere log location.  No longer critical but we definitely need to figure out what's going on here.

**Comment by wimo7083** [comment]
Two parts to this issue: 
1. Relying on logging for testing purposes. This isn't good should transition to unit tests
2. Need to figure out what should be logged for the work flow and how to deal with that.
