### ISSUE TITLE
Setup file uploading

### ISSUE THREAD

**Issue by AllenAnthes** [OperationCode/operation_code_pybot#23]
Add a field in the mentor request form to accept files.
Figure out how to accept the file and pass it along to Airtable

**Comment by wimo7083** [comment]
Summary: slack dialog doesn't allow file uploads which are required for resume requests. @AllenAnthes was able to implement a method in which we can direct user to a flask route and upload though a form. 

Current flow:
1. greetbot sends initial message
2. User decides to click `I need a mentor button`
3. In slack dialog pops up very similar to the current web page mentor request
4. ??? get file ???
5. Send stuff to airtable.

So the three ideas:
1. If it's a resume review we direct them to a new page route that allows a single file to be uploaded. Now the flask application is serving web content in addition to routing bot flow. 
2. Take the resume review request and have user upload in the direct conversation to the bot. 
3. No use slack dialogs and just keep redirecting them to the mentor request page.

**Comment by wimo7083** [comment]
Spoke with leadership in \#community. There is no desire to have resume request without actual resume. So we need to either keep redirecting it to the request page or take resume requests through file upload. I submitted a feature request to the slackApi team so who knows!

**Comment by wimo7083** [comment]
Closing until more requirements are done on why we need uploading and if we want to integrate mentor services with bot.
