### ISSUE TITLE
Bot interaction groups

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operation_code_pybot#26]
To support slash commands we need user groups to prevent issues where the wrong people can access the wrong commands.

**Comment by wimo7083** [comment]
At first there will be four user-groups:
1. Mentors
2. Contributors (for testing functionality)
3. Leadership
4. Default

**Comment by wimo7083** [comment]
@AllenAnthes  this is super close to the database we just need a way to assign who gets what values. Want to work on it?

**Comment by AllenAnthes** [comment]
Sure.  Now that the Users table is (mostly) working it should be trivial to just throw the user-group in as another column and then query it whenever we receive the POST from the slash command.

**Comment by AllenAnthes** [comment]
Just mocked this up
```
class UserGroup(enum.Enum):
    Contributor = 0
    Leadership = 1
    Mentor = 2
    Default = 3


class User(Base):
    __tablename__ = 'users'

    id = Column(Integer, primary_key=True)
    first_name = Column(String(50))
    last_name = Column(String(50))
    email = Column(String(50), nullable=False)
    interests = relationship('Interest', secondary=interest_associations,
                             back_populates='users')
    usergroup = Column(ChoiceType(UserGroup, impl=Integer))
```

My thinking here is that as you move up in privilege levels the group will have access to all the previous group's commands.  As each UserGroup is implemented as their corresponding integer value we should be able to assign a minimum value necessary to access each command.

**Comment by wimo7083** [comment]
PR #31 provides user level.
