### ISSUE TITLE
Build first slash command

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operation_code_pybot#27]
First slash commands will include:

All users have access:
`/info` or `/help` in case one of them is restricted 

mentors have access:
`/readsuggestions`
`/infostats`

Maybe split access where non-mentors can see their own suggestions?

**Comment by wimo7083** [comment]
@AllenAnthes any chance we can have a discussion of what groups should have what commands to start with? This is probably held up by #26 if we want to do it semi-goodly.

**Comment by AllenAnthes** [comment]
Closing this as we're up to a grand total of 2 slash-commands now.  We should discuss some other commands we'd like to see.
