### ISSUE TITLE
change/ stop spamming community

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operation_code_pybot#34]
Change the `testgreet` call so that it doesn't send it to /#community, and sends to the user.

Make new `testgreethere` call, that redirects the notification to the channel you are currently in.

**Comment by AllenAnthes** [comment]
Implemented a new slash-command `/testgreet` that sends a team_join event to the bot for the user that used the command.  The notification will be sent to the channel the user was in when using the command.
